### ISSUE TITLE
Fishing efforts re-enabled on each added vessel

### ISSUE THREAD

**Issue by eldk** [GlobalFishingWatch/map-client#834]
Hello,

I'm currently building a map. To give some speed to work, I have disabled some layers, included fishing efforts one.

I have a list of vessels, that I'm searching with search tool.

As soon as I pin one of them, Fishing efforts is enable again.

I have try it in Firefox/56.0 and Chromium 62.0.3202.75, it's the same.

Thanks,

Eric

Maybe related to this : https://github.com/Vizzuality/GlobalFishingWatch/pull/630

link to map (in progress) : http://globalfishingwatch.org/map/workspace/udw-v2-5f00102a-a78a-4182-a283-78a76bd8170a

**Comment by nerik** [comment]
Thanks for the report. We'll have a look and let you know.

**Comment by eldk** [comment]
Thanks

**Comment by nerik** [comment]
@eldk Sorry for taking so much time to get back to yo on this.
@enriquetuya The behaviour we have now is that search is disabled on hidden layers, so what @eldk is describing here is not possible anymore. Should we tackle this particular use case?

**Comment by enriquetuya** [comment]
@nerik correct. Now is not possible. The question for @eldk would be why he had to disable the layers for search, it was slower? or you didn't want the map to re-center on the vessel you clicked? 

My guess is that the reason is that he didn't want the map to recenter to the new position, that relates to:  https://github.com/GlobalFishingWatch/map-client/issues/930 

Closing this one. @eldk I can reopen it based on your feedback.
