### ISSUE TITLE
UI issues prioritization

### ISSUE THREAD

**Issue by nerik** [GlobalFishingWatch/map-client#875]
- [ ] Encounters pinning (see https://github.com/GlobalFishingWatch/GFW-Tasks/issues/692)
- [ ] overall back button (see https://github.com/GlobalFishingWatch/GFW-Tasks/issues/692) 

Erik:
- [x] No need for 4 basemaps. North Star / deep blue / high contrast serve the same purpose
- [ ] does mini globe needs to be collapsible?
- [ ] lat/lon mouse hover indicator is not useful as it is IMHO. Display region, DMS instead of decimal lat lons, etc (as in Vizz designs)
- [x] distinction between "Activity layers" and "map layers" is ambiguous. Second could be called "static layers". 
- [ ] right panel need transitions

**Comment by enriquetuya** [comment]
@nerik based on your thoughts:
- I agree that there is no need for the 4 basemaps. I would only keep Satellite and North Star.
- The mini was set as collapsible for the mobile version. Besides that, the mini globe not that useful since you can't click on it.
- lat/lon as it is, is useful, this was a requests sent by multiple users, that need to corroborate activity on a given point. I recall vizz design showing besides lat/long the region and also the ability to copy-paste. But I wouldn't remove the lat/lon.
- Agreed with the `map layers` to `static layers`
- Agreed with the transitions, but we want them to be subtle.

**Comment by nerik** [comment]
@enriquetuya few comments on your comments :)

> The mini was set as collapsible for the mobile version. Besides that, the mini globe not that useful since you can't click on it.

I think one of the big things that came out of the last user research session was that it was hard to know where you are on the planet at high zoom levels, so I'd say that is useful. We could definitely make it interactive though. 

> lat/lon as it is, is useful, this was a requests sent by multiple users, that need to corroborate activity on a given point. I recall vizz design showing besides lat/long the region and also the ability to copy-paste. But I wouldn't remove the lat/lon.

I think the idea on the design was to have more readable DMS lat/lon displayed (ie human readable), turned into decimal on click/copy-paste (machine readable)

**Comment by nerik** [comment]
Re miniglobe and lat/lon indicator: https://github.com/GlobalFishingWatch/map-client/issues/649
