### ISSUE TITLE
Encounters layer not working properly

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#893]
For some reason encounters are being displayed grouped on top of the globe. 
![screenshot 2018-05-09 13 19 54](https://user-images.githubusercontent.com/355597/39826669-c5d1613e-538b-11e8-8764-7a406d71c257.png)

**Comment by nerik** [comment]
This is due to the tiles generator producing "baked" world coordinates that are wrong on this branch.

The current fix ignores world coordinates and will convert lat/lon to world coordinates on the client side (as is the case with all other activity layers). This has a very limited impact for performance because the dataset is very small.

We should revisit in the future when/if we move activity layers to PBF tiles.
