### ISSUE TITLE
Weird artifacts when zooming in with a custom geojson layer. 

### ISSUE THREAD

**Issue by enriquetuya** [GlobalFishingWatch/map-client#989]
Checkout the issue happening with the Custom GeoJson layer on the following video:
https://drive.google.com/file/d/1628MxNXmvOAIaVPUv_qhvaL36Vrg1ICc/view?usp=sharing

What can be wrong? 
http://globalfishingwatch.org/map/workspace/udw-v2-d506f954-6b82-4fdc-ab31-73a6aef47d19

**Comment by nerik** [comment]
@enriquetuya The problem was that the source GeoJSON uses line geometries, that were not yet supported for custom layers. Defaulting to polygons, the renderer was probably not able to deal with holes and/or antimeridian line correctly.

Support for line geometries, as well as point geometries, in this PR: https://github.com/GlobalFishingWatch/map-client/pull/993
